default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('PGHOST') { 'localhost' } %>
  username: <%= ENV.fetch('PGUSER') { 'postgres' } %>
  password: <%= ENV.fetch('PGPASSWORD') { 'password' } %> # matches the one in CI

development:
  <<: *default
  database: success_on_rails_development

test:
  <<: *default
  database: success_on_rails_test


#   production:
#
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
